class CountriesHelper {
  static final Map<String, dynamic> countriesMap = {
    "ALL": {"2code": "ALL", "3code": "ALL"},
    "Afghanistan": {"2code": "AF", "3code": "AFG"},
    "Aland Islands": {"2code": "AX", "3code": "ALA"},
    "Albania": {"2code": "AL", "3code": "ALB"},
    "Algeria": {"2code": "DZ", "3code": "DZA"},
    "American Samoa": {"2code": "AS", "3code": "ASM"},
    "Andorra": {"2code": "AD", "3code": "AND"},
    "Angola": {"2code": "AO", "3code": "AGO"},
    "Anguilla": {"2code": "AI", "3code": "AIA"},
    "Antarctica": {"2code": "AQ", "3code": "ATA"},
    "Antigua And Barbuda": {"2code": "AG", "3code": "ATG"},
    "Argentina": {"2code": "AR", "3code": "ARG"},
    "Armenia": {"2code": "AM", "3code": "ARM"},
    "Aruba": {"2code": "AW", "3code": "ABW"},
    "Australia": {"2code": "AU", "3code": "AUS"},
    "Austria": {"2code": "AT", "3code": "AUT"},
    "Austria Amateur": {"2code": "AT", "3code": "AUT"},
    "Azerbaijan": {"2code": "AZ", "3code": "AZE"},
    "Bahamas": {"2code": "BS", "3code": "BHS"},
    "Bahrain": {"2code": "BH", "3code": "BHR"},
    "Bangladesh": {"2code": "BD", "3code": "BGD"},
    "Barbados": {"2code": "BB", "3code": "BRB"},
    "Belarus": {"2code": "BY", "3code": "BLR"},
    "Belgium": {"2code": "BE", "3code": "BEL"},
    "Belize": {"2code": "BZ", "3code": "BLZ"},
    "Benin": {"2code": "BJ", "3code": "BEN"},
    "Bermuda": {"2code": "BM", "3code": "BMU"},
    "Bhutan": {"2code": "BT", "3code": "BTN"},
    "Bolivia": {"2code": "BO", "3code": "BOL"},
    "Bosnia Herzegovina": {"2code": "BA", "3code": "BIH"},
    "Botswana": {"2code": "BW", "3code": "BWA"},
    "Bouvet Island": {"2code": "BV", "3code": "BVT"},
    "Brazil": {"2code": "BR", "3code": "BRA"},
    "British Indian Ocean Territory": {"2code": "IO", "3code": "IOT"},
    "Brunei Darussalam": {"2code": "BN", "3code": "BRN"},
    "Bulgaria": {"2code": "BG", "3code": "BGR"},
    "Burkina Faso": {"2code": "BF", "3code": "BFA"},
    "Burundi": {"2code": "BI", "3code": "BDI"},
    "Cambodia": {"2code": "KH", "3code": "KHM"},
    "Cameroon": {"2code": "CM", "3code": "CMR"},
    "Canada": {"2code": "CA", "3code": "CAN"},
    "Cape Verde": {"2code": "CV", "3code": "CPV"},
    "Cayman Islands": {"2code": "KY", "3code": "CYM"},
    "Central African Republic": {"2code": "CF", "3code": "CAF"},
    "Chad": {"2code": "TD", "3code": "TCD"},
    "Chile": {"2code": "CL", "3code": "CHL"},
    "China": {"2code": "CN", "3code": "CHN"},
    "Christmas Island": {"2code": "CX", "3code": "CXR"},
    "Cocos (Keeling) Islands": {"2code": "CC", "3code": "CCK"},
    "Colombia": {"2code": "CO", "3code": "COL"},
    "Comoros": {"2code": "KM", "3code": "COM"},
    "Congo": {"2code": "CG", "3code": "COG"},
    "Congo, Democratic Republic": {"2code": "CD", "3code": "COD"},
    "Cook Islands": {"2code": "CK", "3code": "COK"},
    "Costa Rica": {"2code": "CR", "3code": "CRI"},
    "Cote D'Ivoire": {"2code": "CI", "3code": "CIV"},
    "Ivory Coast": {"2code": "CI", "3code": "CIV"},
    "Croatia": {"2code": "HR", "3code": "HRV"},
    "Cuba": {"2code": "CU", "3code": "CUB"},
    "Cyprus": {"2code": "CY", "3code": "CYP"},
    "Czech Republic": {"2code": "CZ", "3code": "CZE"},
    "Denmark": {"2code": "DK", "3code": "DNK"},
    "Denmark Amateur": {"2code": "DK", "3code": "DNK"},
    "Djibouti": {"2code": "DJ", "3code": "DJI"},
    "Dominica": {"2code": "DM", "3code": "DMA"},
    "Dominican Republic": {"2code": "DO", "3code": "DOM"},
    "Ecuador": {"2code": "EC", "3code": "ECU"},
    "Egypt": {"2code": "EG", "3code": "EGY"},
    "El Salvador": {"2code": "SV", "3code": "SLV"},
    "Equatorial Guinea": {"2code": "GQ", "3code": "GNQ"},
    "Eritrea": {"2code": "ER", "3code": "ERI"},
    "Estonia": {"2code": "EE", "3code": "EST"},
    "Ethiopia": {"2code": "ET", "3code": "ETH"},
    "Falkland Islands (Malvinas)": {"2code": "FK", "3code": "FLK"},
    "Faroe Islands": {"2code": "FO", "3code": "FRO"},
    "Fiji": {"2code": "FJ", "3code": "FJI"},
    "Finland": {"2code": "FI", "3code": "FIN"},
    "Finland Amateur": {"2code": "FI", "3code": "FIN"},
    "France": {"2code": "FR", "3code": "FRA"},
    "French Guiana": {"2code": "GF", "3code": "GUF"},
    "French Polynesia": {"2code": "PF", "3code": "PYF"},
    "French Southern Territories": {"2code": "TF", "3code": "ATF"},
    "Gabon": {"2code": "GA", "3code": "GAB"},
    "Gambia": {"2code": "GM", "3code": "GMB"},
    "Georgia": {"2code": "GE", "3code": "GEO"},
    "Germany": {"2code": "DE", "3code": "DEU"},
    "Germany Amateur": {"2code": "DE", "3code": "DEU"},
    "Ghana": {"2code": "GH", "3code": "GHA"},
    "Gibraltar": {"2code": "GI", "3code": "GIB"},
    "Greece": {"2code": "GR", "3code": "GRC"},
    "Greenland": {"2code": "GL", "3code": "GRL"},
    "Grenada": {"2code": "GD", "3code": "GRD"},
    "Guadeloupe": {"2code": "GP", "3code": "GLP"},
    "Guam": {"2code": "GU", "3code": "GUM"},
    "Guatemala": {"2code": "GT", "3code": "GTM"},
    "Guernsey": {"2code": "GG", "3code": "GGY"},
    "Guinea": {"2code": "GN", "3code": "GIN"},
    "Guinea-Bissau": {"2code": "GW", "3code": "GNB"},
    "Guyana": {"2code": "GY", "3code": "GUY"},
    "Haiti": {"2code": "HT", "3code": "HTI"},
    "Heard Island & Mcdonald Islands": {"2code": "HM", "3code": "HMD"},
    "Holy See (Vatican City State)": {"2code": "VA", "3code": "VAT"},
    "Honduras": {"2code": "HN", "3code": "HND"},
    "Hong Kong": {"2code": "HK", "3code": "HKG"},
    "Hungary": {"2code": "HU", "3code": "HUN"},
    "Iceland": {"2code": "IS", "3code": "ISL"},
    "India": {"2code": "IN", "3code": "IND"},
    "Indonesia": {"2code": "ID", "3code": "IDN"},
    "Iran": {"2code": "IR", "3code": "IRN"},
    "Iraq": {"2code": "IQ", "3code": "IRQ"},
    "Ireland": {"2code": "IE", "3code": "IRL"},
    "Isle Of Man": {"2code": "IM", "3code": "IMN"},
    "Israel": {"2code": "IL", "3code": "ISR"},
    "Italy": {"2code": "IT", "3code": "ITA"},
    "Jamaica": {"2code": "JM", "3code": "JAM"},
    "Japan": {"2code": "JP", "3code": "JPN"},
    "Jersey": {"2code": "JE", "3code": "JEY"},
    "Jordan": {"2code": "JO", "3code": "JOR"},
    "Kazakhstan": {"2code": "KZ", "3code": "KAZ"},
    "Kenya": {"2code": "KE", "3code": "KEN"},
    "Kiribati": {"2code": "KI", "3code": "KIR"},
    "Korea": {"2code": "KR", "3code": "KOR"},
    "Republic of Korea": {"2code": "KR", "3code": "KOR"},
    "Republic Of Korea": {"2code": "KR", "3code": "KOR"},
    "Korean Republic": {"2code": "KR", "3code": "KOR"},
    "South Korea": {"2code": "KR", "3code": "KOR"},
    "Kuwait": {"2code": "KW", "3code": "KWT"},
    "Kyrgyzstan": {"2code": "KG", "3code": "KGZ"},
    "Lao People's Democratic Republic": {"2code": "LA", "3code": "LAO"},
    "Latvia": {"2code": "LV", "3code": "LVA"},
    "Lebanon": {"2code": "LB", "3code": "LBN"},
    "Lesotho": {"2code": "LS", "3code": "LSO"},
    "Liberia": {"2code": "LR", "3code": "LBR"},
    "Libyan Arab Jamahiriya": {"2code": "LY", "3code": "LBY"},
    "Liechtenstein": {"2code": "LI", "3code": "LIE"},
    "Lithuania": {"2code": "LT", "3code": "LTU"},
    "Luxembourg": {"2code": "LU", "3code": "LUX"},
    "Macao": {"2code": "MO", "3code": "MAC"},
    "Macedonia": {"2code": "MK", "3code": "MKD"},
    "Madagascar": {"2code": "MG", "3code": "MDG"},
    "Malawi": {"2code": "MW", "3code": "MWI"},
    "Malaysia": {"2code": "MY", "3code": "MYS"},
    "Maldives": {"2code": "MV", "3code": "MDV"},
    "Mali": {"2code": "ML", "3code": "MLI"},
    "Malta": {"2code": "MT", "3code": "MLT"},
    "Marshall Islands": {"2code": "MH", "3code": "MHL"},
    "Martinique": {"2code": "MQ", "3code": "MTQ"},
    "Mauritania": {"2code": "MR", "3code": "MRT"},
    "Mauritius": {"2code": "MU", "3code": "MUS"},
    "Mayotte": {"2code": "YT", "3code": "MYT"},
    "Mexico": {"2code": "MX", "3code": "MEX"},
    "Micronesia, Federated States Of": {"2code": "FM", "3code": "FSM"},
    "Moldova": {"2code": "MD", "3code": "MDA"},
    "Monaco": {"2code": "MC", "3code": "MCO"},
    "Mongolia": {"2code": "MN", "3code": "MNG"},
    "Montenegro": {"2code": "ME", "3code": "MNE"},
    "Montserrat": {"2code": "MS", "3code": "MSR"},
    "Morocco": {"2code": "MA", "3code": "MAR"},
    "Mozambique": {"2code": "MZ", "3code": "MOZ"},
    "Myanmar": {"2code": "MM", "3code": "MMR"},
    "Namibia": {"2code": "NA", "3code": "NAM"},
    "Nauru": {"2code": "NR", "3code": "NRU"},
    "Nepal": {"2code": "NP", "3code": "NPL"},
    "Netherlands": {"2code": "NL", "3code": "NLD"},
    "Netherlands Antilles": {"2code": "AN", "3code": "ANT"},
    "New Caledonia": {"2code": "NC", "3code": "NCL"},
    "New Zealand": {"2code": "NZ", "3code": "NZL"},
    "Newzealand": {"2code": "NZ", "3code": "NZL"},
    "Nicaragua": {"2code": "NI", "3code": "NIC"},
    "Niger": {"2code": "NE", "3code": "NER"},
    "Nigeria": {"2code": "NG", "3code": "NGA"},
    "Niue": {"2code": "NU", "3code": "NIU"},
    "Norfolk Island": {"2code": "NF", "3code": "NFK"},
    "Northern Mariana Islands": {"2code": "MP", "3code": "MNP"},
    "Norway": {"2code": "NO", "3code": "NOR"},
    "Norway Amateur": {"2code": "NO", "3code": "NOR"},
    "Oman": {"2code": "OM", "3code": "OMN"},
    "Pakistan": {"2code": "PK", "3code": "PAK"},
    "Palau": {"2code": "PW", "3code": "PLW"},
    "Palestine": {"2code": "PS", "3code": "PSE"},
    "Panama": {"2code": "PA", "3code": "PAN"},
    "Papua New Guinea": {"2code": "PG", "3code": "PNG"},
    "Paraguay": {"2code": "PY", "3code": "PRY"},
    "Peru": {"2code": "PE", "3code": "PER"},
    "Philippines": {"2code": "PH", "3code": "PHL"},
    "Pitcairn": {"2code": "PN", "3code": "PCN"},
    "Poland": {"2code": "PL", "3code": "POL"},
    "Portugal": {"2code": "PT", "3code": "PRT"},
    "Puerto Rico": {"2code": "PR", "3code": "PRI"},
    "Qatar": {"2code": "QA", "3code": "QAT"},
    "Reunion": {"2code": "RE", "3code": "REU"},
    "Romania": {"2code": "RO", "3code": "ROU"},
    "Russia": {"2code": "RU", "3code": "RUS"},
    "Rwanda": {"2code": "RW", "3code": "RWA"},
    "Saint Barthelemy": {"2code": "BL", "3code": "BLM"},
    "Saint Helena": {"2code": "SH", "3code": "SHN"},
    "Saint Kitts And Nevis": {"2code": "KN", "3code": "KNA"},
    "Saint Lucia": {"2code": "LC", "3code": "LCA"},
    "Saint Martin": {"2code": "MF", "3code": "MAF"},
    "Saint Pierre And Miquelon": {"2code": "PM", "3code": "SPM"},
    "Saint Vincent And Grenadines": {"2code": "VC", "3code": "VCT"},
    "Samoa": {"2code": "WS", "3code": "WSM"},
    "San Marino": {"2code": "SM", "3code": "SMR"},
    "Sao Tome And Principe": {"2code": "ST", "3code": "STM"},
    "Saudi Arabia": {"2code": "SA", "3code": "SAU"},
    "Senegal": {"2code": "SN", "3code": "SEN"},
    "Serbia": {"2code": "RS", "3code": "SRB"},
    "Seychelles": {"2code": "SC", "3code": "SYC"},
    "Sierra Leone": {"2code": "SL", "3code": "SLE"},
    "Singapore": {"2code": "SG", "3code": "SGP"},
    "Slovakia": {"2code": "SK", "3code": "SVK"},
    "Slovenia": {"2code": "SI", "3code": "SVN"},
    "Solomon Islands": {"2code": "SB", "3code": "SLB"},
    "Solomon Island": {"2code": "SB", "3code": "SLB"},
    "Somalia": {"2code": "SO", "3code": "SOM"},
    "South Africa": {"2code": "ZA", "3code": "ZAF"},
    "South Georgia And Sandwich Isl.": {"2code": "GS", "3code": "SGS"},
    "Spain": {"2code": "ES", "3code": "ESP"},
    "Spain Amateur": {"2code": "ES", "3code": "ESP"},
    "Sri Lanka": {"2code": "LK", "3code": "LKA"},
    "Sudan": {"2code": "SD", "3code": "SDN"},
    "Suriname": {"2code": "SR", "3code": "SUR"},
    "Svalbard And Jan Mayen": {"2code": "SJ", "3code": "SJM"},
    "Swaziland": {"2code": "SZ", "3code": "SZW"},
    "Sweden": {"2code": "SE", "3code": "SWE"},
    "Sweden Amateur": {"2code": "SE", "3code": "SWE"},
    "Switzerland": {"2code": "CH", "3code": "CHE"},
    "Syrian Arab Republic": {"2code": "SY", "3code": "SYR"},
    "Taiwan": {"2code": "TW", "3code": "TWN"},
    "Chinese Taipei": {"2code": "TW", "3code": "TWN"},
    "Tajikistan": {"2code": "TJ", "3code": "TJK"},
    "Tanzania": {"2code": "TZ", "3code": "TZA"},
    "Thailand": {"2code": "TH", "3code": "THA"},
    "Timor-Leste": {"2code": "TL", "3code": "TLS"},
    "Togo": {"2code": "TG", "3code": "TGO"},
    "Tokelau": {"2code": "TK", "3code": "TKL"},
    "Tonga": {"2code": "TO", "3code": "TON"},
    "Trinidad And Tobago": {"2code": "TT", "3code": "TTO"},
    "Tunisia": {"2code": "TN", "3code": "TUN"},
    "Turkey": {"2code": "TR", "3code": "TUR"},
    "Turkey Amateur": {"2code": "TR", "3code": "TUR"},
    "Turkmenistan": {"2code": "TM", "3code": "TKM"},
    "Turks And Caicos Islands": {"2code": "TC", "3code": "TCA"},
    "Tuvalu": {"2code": "TV", "3code": "TUV"},
    "Uganda": {"2code": "UG", "3code": "UGA"},
    "Ukraine": {"2code": "UA", "3code": "UKR"},
    "United Arab Emirates": {"2code": "AE", "3code": "UAE"},
    "UAE": {"2code": "AE", "3code": "UAE"},
    "United Kingdom": {"2code": "GB", "3code": "GBR"},
    "United States": {"2code": "US", "3code": "USA"},
    "USA": {"2code": "US", "3code": "USA"},
    "Usa": {"2code": "US", "3code": "USA"},
    "United States Outlying Islands": {"2code": "UM", "3code": "UMI"},
    "Uruguay": {"2code": "UY", "3code": "URY"},
    "Uzbekistan": {"2code": "UZ", "3code": "UZB"},
    "Vanuatu": {"2code": "VU", "3code": "VUT"},
    "Venezuela": {"2code": "VE", "3code": "VEN"},
    "Vietnam": {"2code": "VN", "3code": "VNM"},
    "Virgin Islands, British": {"2code": "VG", "3code": "VGB"},
    "Virgin Islands, U.S.": {"2code": "VI", "3code": "VIR"},
    "Wallis And Futuna": {"2code": "WF", "3code": "WLF"},
    "Western Sahara": {"2code": "EH", "3code": "ESH"},
    "Yemen": {"2code": "YE", "3code": "YEM"},
    "Zambia": {"2code": "ZM", "3code": "ZMB"},
    "Zimbabwe": {"2code": "ZW", "3code": "ZWE"},
    "Northern Ireland": {"2code": "gb_nir", "3code": "NIR"},
    "Wales": {"2code": "gb_wls", "3code": "WLS"},
    "England": {"2code": "GB", "3code": "ENG"},
    "England Amateur": {"2code": "GB", "3code": "ENG"},
    "Scotland": {"2code": "gb_sct", "3code": "SCT"}
  };
}
